import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppKitProvider } from "@/context/AppKitProvider";
import Navbar from "@/components/Navbar";
import DynamicFooter from "@/components/DynamicFooter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Axe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppKitProvider>
      
          <main className="min-h-screen bg-[#0d0c0e]">
                <Navbar />
            {children}
          </main>
          <DynamicFooter/>
        </AppKitProvider>
      </body>
    </html>
  );
}